services:
  training-diamonds:
    build: .
    env_file:
      - .env
    container_name: training-diamonds
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - training-diamonds-data:/usr/src/app/data
    networks:
      - web

volumes:
  training-diamonds-data:

networks:
  web:
    external: true
